# config/s3.yml
development:
  access_key_id: AKIAIFRD2TQOHCUCJ3AQ
  secret_access_key: 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
  bucket: beardiscounts
test:
  access_key_id: AKIAIFRD2TQOHCUCJ3AQ
  secret_access_key: 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
  bucket: beardiscounts
production:
  access_key_id: AKIAIFRD2TQOHCUCJ3AQ
  secret_access_key: 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
  bucket: beardiscounts
